### ISSUE TITLE
The cubemap component doesn't support multi-cubemap in a scene

### ISSUE THREAD

**Issue by chenye-thu** [bryik/aframe-cubemap-component#1]
Hi, Ben！
You really did a good job! The cubemap component helps me a lot. But when I put 2 cubemap in a scene like below, it seems that the `sky4`'s images will be overwritten by the `sky5`'s images.
`<a-entity id="sky4" cubemap="folder: ./assets/sky4/" visible="true"></a-entity>`
`<a-entity id="sky5" cubemap="folder: ./assets/sky5/" visible="false"></a-entity>`
So, I think maybe this component doesn`t support multi-cubemap in a scene. But I believe it would be feasible to realize this feature. Unfortunately I'm a rookie of js, and I don't know how to do it, so I create this issue to ask you for help. It will be highly appreciated if you could help me to realize this feature.

**Comment by bryik** [comment]
Hello Chen! 

I'm a JS rookie myself, so I appreciate the feedback!

You're right that having multiple cubemaps in a scene doesn't work. Adding a second cubemap to a scene appears to cause the uniforms of the first cubemap's ShaderMaterial to be overridden. Cloning the ShaderMaterial and applying the cubemap textures to the uniforms of the clone seems to fix this. 

I created a test branch [here.](https://github.com/bryik/aframe-cubemap-component/tree/more-cubemaps) Let me know if it works for you.

**Comment by chenye-thu** [comment]
Wow! It works!
Ben, you really did a awesome job!
I'm so sorry for my responding too late. Actually, I came to your repo several times, but failed to find your reply...(That's awkward) I hope you could excuse me.
And thank you so much! I really  don't know what I would have done without your help.

**Comment by bryik** [comment]
Great! I'll probably merge that branch into master sometime soon. [edit: done]

Thanks again for the feedback!
