### ISSUE TITLE
Cubemap brighter "washed out" compared to equirectangular (a-sky)

### ISSUE THREAD

**Issue by kfarr** [bryik/aframe-cubemap-component#13]
Sky component (using equirectangular):
![image](https://user-images.githubusercontent.com/470477/81372203-9f53cd00-90ae-11ea-9a4a-867aaca6daa5.png)

Cubemap component (same equirectangular from above converted to cube map [using this tool](https://jaxry.github.io/panorama-to-cubemap/)):
![image](https://user-images.githubusercontent.com/470477/81372215-a67adb00-90ae-11ea-99ca-87f63679d5d0.png)

Appears to be same as this issue:
https://discourse.threejs.org/t/r99-cubemap-brighter/5496

Discussion points:
- Should this be a user option to set encoding?
- Or, should sRGB be the default? If so then I think it's as simple as inserting a new line above [84](https://github.com/bryik/aframe-cubemap-component/blob/master/index.js#L84) such as `texture.encoding = THREE.sRGBEncoding;`

Related discussion:
- https://discourse.threejs.org/t/gltf-glb-files-and-renderer-gammafactor/9490/3

**Comment by kfarr** [comment]
I tried that in a local copy and yes that "fixes" the issue (now the cubemap version looks the same as the equirectangular a-sky version). I think the question now is if sRGBEncoding should be default, up to you.

**Comment by bryik** [comment]
Those discussions make it sound like `texture.encoding = THREE.sRGBEncoding;` should be the default, but when I tried it with [the Yokohama example](https://bryik.github.io/aframe-cubemap-component/yokohama/index.html) the resulting cubemap was darker than the original image:

![image](https://user-images.githubusercontent.com/12419712/81477600-3ff4da80-91de-11ea-9106-e44e0c867e49.png)

**Left** is the original image, **right** is the rendered cubemap.

**Comment by bryik** [comment]
For comparison, here is the current code (**without** `texture.encoding = THREE.sRGBEncoding;`).

![image](https://user-images.githubusercontent.com/12419712/81477677-89452a00-91de-11ea-9094-6d1b9372381f.png)

**Left** is the original image, **right** is the rendered cubemap.

**Comment by bryik** [comment]
I can certainly make texture encoding a property though.

**Comment by kfarr** [comment]
Good points all around, yes a property probably makes the most sense

**Comment by bryik** [comment]
Did some more reading into this and found A-Frame's renderer has a [colorManagement](https://aframe.io/docs/1.0.0/components/renderer.html#colormanagement) property that balances the darkness brought by `texture.encoding = THREE.sRGBEncoding;`.

```html
<a-scene renderer="colorManagement: true">
  <a-entity cubemap="folder: /assets/Yokohama3/"></a-entity>
</a-scene>
```

![image](https://user-images.githubusercontent.com/12419712/81481337-efd54280-91f4-11ea-858c-5331d04bc07f.png)

I still think making texture encoding a property is the way to go, but maybe A-Frame will make `colorManagement: true` the default some day.

**Comment by kfarr** [comment]
Looks good! Thanks for digging in to that, and your new example showing what happens with `colorManagement: true` on the scene while using sRGBEncoding is helpful and accurate as far as I know.

In fact, it appears that when `colorManagement: true`, the A-Frame core material handlers use a helper [`applyColorCorrection` function](https://github.com/aframevr/aframe/blob/ccd877c3036eea7c1b795846dea9411fb3475395/src/systems/renderer.js#L51) to set textures to sRGBEncoding, [like in this example](https://github.com/aframevr/aframe/blob/c55f024b613898fbefc03ff6c2c3ba60812c9a2c/src/utils/material.js#L63).

**Comment by bryik** [comment]
> In fact, it appears that when `colorManagement: true`, the A-Frame core material handlers use a helper [`applyColorCorrection` function](https://github.com/aframevr/aframe/blob/ccd877c3036eea7c1b795846dea9411fb3475395/src/systems/renderer.js#L51) to set textures to sRGBEncoding, [like in this example](https://github.com/aframevr/aframe/blob/c55f024b613898fbefc03ff6c2c3ba60812c9a2c/src/utils/material.js#L63).

Oh interesting! Instead of an `encoding` property, we could retrieve the renderer system and apply color correction automatically just like the core library. I think this would actually be better!

Thanks for those links!

**Comment by bryik** [comment]
@kfarr thoughts on [this MR](https://github.com/bryik/aframe-cubemap-component/pull/17)?

**Comment by kfarr** [comment]
Yes this looks great! I didn't test it but the logic seems right. I can test a little later or after you commit those changes.

**Comment by bryik** [comment]
> Yes this looks great! I didn't test it but the logic seems right. I can test a little later or after you commit those changes.

Cool. 

I'll merge it in--we can patch it later if you find it's not working correctly.
