### ISSUE TITLE
Support for A-Frame asset loader syntax for cubemaps

### ISSUE THREAD

**Issue by kfarr** [bryik/aframe-cubemap-component#14]
In my project I have previously used the A-Frame `a-assets` asset loader to load the equirectangular sky image. That same asset is also used as a `sphericalEnvMap` on materials for reflections.

For example:
`<a-ocean-plane height="100" width="100" position="0 -1 0" material="sphericalEnvMap: #sky;"></a-ocean-plane>`

I am attempting to convert this to cubemap. It turns out a [cubemap can be referenced from a-asset loader as well](https://aframe.io/docs/1.0.0/components/material.html#environment-maps), example pasted here for convenience:
```
<a-assets>
    <a-cubemap id="sky">
      <img src="right.png">
      <img src="left.png">
      <img src="top.png">
      <img src="bottom.png">
      <img src="front.png">
      <img src="back.png">
    </a-cubemap>
  </a-assets>
```

It would be nice to support this syntax to allow passing a selector such as #sky instead of the path for files for the cubemap component, this way the files can be loaded once and referenced from multiple components.

More info from A-Frame source code:
https://github.com/aframevr/aframe/search?q=a-cubemap

**Comment by bryik** [comment]
Yeah, this would be a good addition. I'll look into it!

**Comment by bryik** [comment]
Currently trying to figure out how components hook into A-Frame's asset system.

**Comment by bryik** [comment]
@kfarr images loaded in `<a-assets>` should be cached and **not** downloaded a second time by the `cubemap` component as long as the paths are the same.

So this example only downloads images once:

```html
<html>
  <head>
    <title>A-Frame Cubemap Component - a-assets</title>
    <script src="../../build.js"></script>
  </head>
  <body>
    <a-scene>
      <a-assets>
        <a-cubemap id="sky">
          <img src="../../assets/Yokohama3/negx.jpg" />
          <img src="../../assets/Yokohama3/negy.jpg" />
          <img src="../../assets/Yokohama3/negz.jpg" />
          <img src="../../assets/Yokohama3/posx.jpg" />
          <img src="../../assets/Yokohama3/posy.jpg" />
          <img src="../../assets/Yokohama3/posz.jpg" />
        </a-cubemap>
      </a-assets>
      <a-entity cubemap="folder:../../assets/Yokohama3/"></a-entity>
    </a-scene>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/12419712/81621677-a4699280-93b4-11ea-9a51-e07ad9819b95.png)


And this example downloads images multiple times because the paths are different (even though they lead to the same images)

```html
<html>
  <head>
    <title>A-Frame Cubemap Component - a-assets</title>
    <script src="../../build.js"></script>
  </head>
  <body>
    <a-scene>
      <a-assets>
        <a-cubemap id="sky">
          <img src="../../assets/Yokohama3/negx.jpg" />
          <img src="../../assets/Yokohama3/negy.jpg" />
          <img src="../../assets/Yokohama3/negz.jpg" />
          <img src="../../assets/Yokohama3/posx.jpg" />
          <img src="../../assets/Yokohama3/posy.jpg" />
          <img src="../../assets/Yokohama3/posz.jpg" />
        </a-cubemap>
      </a-assets>
      <a-entity cubemap="folder: /assets/Yokohama3/"></a-entity>
    </a-scene>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/12419712/81621697-b64b3580-93b4-11ea-8000-18b2eff4053d.png)

**Comment by kfarr** [comment]
Ok so a fix is not needed for performance reasons as long as matching paths are provided, so maybe it's more appropriate for a note in the README instead? The only reason to pursue this would be obsessive compulsive rigidity to mimic A-Frame example which isn't necessary IMHO.

Confirming for completeness sake, in [this project](https://github.com/kfarr/streetmix3d/blob/master/index.html#L60) I have:
```
        <a-cubemap id="skycube">
          <img src="assets/images/skybox/posx.jpg">
          <img src="assets/images/skybox/negx.jpg">
          <img src="assets/images/skybox/posy.jpg">
          <img src="assets/images/skybox/negy.jpg">
          <img src="assets/images/skybox/posz.jpg">
          <img src="assets/images/skybox/negz.jpg">
        </a-cubemap>
```
and
```
      <a-entity id="skybox" cubemap="folder: assets/images/skybox/"></a-entity>
```

And you're correct it only downloads the assets once!
![image](https://user-images.githubusercontent.com/470477/81622365-a710bb80-93a5-11ea-8721-fea60fd1b300.png)

**Comment by bryik** [comment]
> Ok so a fix is not needed for performance reasons as long as matching paths are provided, so maybe it's more appropriate for a note in the README instead? The only reason to pursue this would be obsessive compulsive rigidity to mimic A-Frame example which isn't necessary IMHO.

Ya, [here's what it would take to support passing a selector](https://github.com/bryik/aframe-cubemap-component/pull/21). Not sure it's worth the complication.

**Comment by kfarr** [comment]
Not sure the right answer either. I have historically been guilty of scope creep and over complication, although the code you posted seems nice. The other 2 people to consult could be @dmarcos and/or @donmccurdy -- I posted a similar ticket here: https://github.com/donmccurdy/aframe-extras/issues/323

**Comment by donmccurdy** [comment]
The `cube-env-map` component in A-Frame Extras hasn't been updated in quite a while. It's certainly out of date with three.js' new `scene.environment` option. I like the a-assets cubemap syntax but probably won't make any updates here myself.

**Comment by bryik** [comment]
I decided to [merge the PR](https://github.com/bryik/aframe-cubemap-component/pull/21), so it is now possible to reference a cubemap in `<a-assets>` by providing an ID instead of a path.
