### ISSUE TITLE
Yokohama example didn't work

### ISSUE THREAD

**Issue by Dirk-27** [bryik/aframe-cubemap-component#26]
The Code for the yokohama example didn't work. To fix it use:

```
<html>
	<head>
	<title>A-Frame Cubemap Component - Yokohama</title>
	<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
	<script src="https://unpkg.com/aframe-cubemap-component@2.1.1/dist/aframe-cubemap-component.min.js"></script>
	</head>
	
	<body>
	<a-scene>
		<a-entity cubemap="folder: ../assets/Yokohama3/"></a-entity>
	</a-scene>
	</body>
</html>
```

This also works in a local environment.

Questions:
* Can I push changes or contribute anyway?
* How can I build the project to get a min.js in dist?

**Comment by bryik** [comment]
Where didn't it work? [The Yokohama example](https://bryik.github.io/aframe-cubemap-component/yokohama/index.html) seems to be working for me.

> Can I push changes or contribute anyway?

Sure, I consider all PRs. For anything requiring a lot of work, I recommend opening an issue to discuss it (in some cases, you might be better off forking the project).

> How can I build the project to get a min.js in dist?

`npm run dist`

I'll add this to the README soonish.

**Comment by bryik** [comment]
Closing because this issue is outdated (I just removed the ability to make minified builds so my advice to use `npm run dist` is no longer good).
