### ISSUE TITLE
visible edges

### ISSUE THREAD

**Issue by MagicIndustries** [bryik/aframe-cubemap-component#3]
I am using some textures I've been using in unity that seem to work fine in there, but in the aframe cubemap component it shows slight white edges. Changing the edge length doesn't seem to change the size of the box, so I'm not sure how to combat this. You can see the edges in the image - is this something wrong with the images themselves or is there something I can do to fine tune it with the component?

<img width="435" alt="screen shot 2017-02-23 at 22 48 11" src="https://cloud.githubusercontent.com/assets/570017/23258013/689cbfca-fa1a-11e6-8297-e5139862cc4d.png">

**Comment by bryik** [comment]
I haven't seen that before. Changing the edge length should change the size of the box (at least it did the last time I tested it). Are the textures square? 

Maybe try one of the [example cubemaps](https://github.com/bryik/aframe-cubemap-component/tree/master/examples/assets/Yokohama3) in your setup and see if the same thing happens.

**Comment by MagicIndustries** [comment]
Yeah the images themselves are 2048 x 2048 each. I'll try another cubemap and see what happens.

**Comment by MagicIndustries** [comment]
Ok the example ones you linked to don't show the same problem in my setup, though I can't see any white edges on my images. I've attached one here for example - I've no idea what's causing it.
![posz](https://cloud.githubusercontent.com/assets/570017/23287217/2a316846-fa90-11e6-8150-4f9b922836a3.jpg)

**Comment by MagicIndustries** [comment]
@bryik on closer inspection in photoshop it appears there is a 1 pixel antialiasing type thing around the edges of my images, the developer must have been clamping them in unity or something. Problem is at our end, sorry.
