### ISSUE TITLE
Hi, I updated the cubemap-component to make it compatible with the new versions of A-Frame/Three.js

### ISSUE THREAD

**Issue by AryehMischel** [bryik/aframe-cubemap-component#47]
Hi, I noticed that the component was no longer working in the latest A-Frame releases (1.4.0 and up).  It seems in the latest versions of Three.js BoxBufferGeometry has been deprecated and the cube shader in ShaderLib has different uniforms now. I found some simple workarounds and made a PR.  Hopefully, we can get it working again, so the community can keep using this awesome component!

**Comment by bryik** [comment]
Thanks for your help! I'm working on publishing a new version. It's been two years since I last did this 😅
