### ISSUE TITLE
Transparency doesn't seem to work?

### ISSUE THREAD

**Issue by fraktalfabrik** [bryik/aframe-cubemap-component#6]
A-Frame Version: 0.7.0 (Date 22-09-2017, Commit #570c623e)
index.js:87 three Version: ^0.87.0
index.js:88 WebVR Polyfill Version: ^0.9.36
three.js:20919 THREE.WebGLRenderer 87
2browser.js:111 core:schema:warn Unknown property `transparent` for component/system `cubemap`. 
three.js:18007 THREE.WebGLProgram: gl.getProgramInfoLog()

**Comment by bryik** [comment]
~~Can you provide an example or [CodePen](https://codepen.io/)?~~

[Transparency](https://bryik.github.io/aframe-cubemap-component/milkyWay/index.html) seems to work for me.

**Edit**: nvm, I think I forgot to bump the dist.

**Comment by bryik** [comment]
Windows *really* does not want to publish to NPM right now...

**Comment by bryik** [comment]
All right, NPM is updated. This should fix your issue. If it doesn't, reopen and let me know!
