### ISSUE TITLE
Does it support stereo cubemap ?

### ISSUE THREAD

**Issue by felixchang123** [bryik/aframe-cubemap-component#8]
Does it support stereo cubemap as https://github.com/wallabyway/aframe-stereocube ?

**Comment by bryik** [comment]
No, but you may be able to create a stereo cubemap with two regular cubemaps that are set to display to one eye only (using the [stereo-component](https://github.com/oscarmarinmiro/aframe-stereo-component)).

Is the aframe-stereocube component not working for you?

**Comment by bryik** [comment]
For future reference, here is [an example](https://github.com/bryik/aframe-metaverse-contest/blob/gh-pages/examples/fushimi-inari.html) that uses this component + some JS to display a stereo cubemap.
