### ISSUE TITLE
Update for threejs v111 (A-Frame 1.0.1+)

### ISSUE THREAD

**Issue by kfarr** [bryik/aframe-cubemap-component#9]
No longer works with more recent version of threejs. Same as this issue here:
https://stackoverflow.com/questions/59454931/three-js-r111-three-shaderlib-cube-uniforms-tcube-to-envmap-issue

A-Frame has rudimentary support for threejs scene background:
- Original suggestion: https://github.com/aframevr/aframe/issues/2908
- Simple source code, only supports solid colors: https://github.com/aframevr/aframe/blob/master/src/components/scene/background.js

The core A-Frame `background` scene component could be improved, or this custom component could be updated to support newer versions of threejs:
- https://threejs.org/docs/#api/en/scenes/Scene.background
- https://threejs.org/docs/index.html#api/en/textures/CubeTexture

**Comment by bryik** [comment]
I'll look into updating this component.

**Comment by bryik** [comment]
@kfarr any thoughts on [this MR](https://github.com/bryik/aframe-cubemap-component/pull/10)? If it looks good, I'll merge it and publish v1.0.0 to NPM. Feels like a major version increment is necessary as this change will not be backwards compatible.

**Comment by kfarr** [comment]
@bryik I just tried the updated code on my project and it seems to work! And the number of triangles is greatly reduced using the cubemap instead of the skybox! :) Agreed this is a breaking change for old aframe versions so new version number makes sense.
